CREATE TABLE RemoteServerAccessInfo
(
	ID BIGINT IDENTITY(1,1),
	SERVERNAME NVARCHAR(100),
	USER_S_ACCESS_BY NVARCHAR(50),
	ISACTIVE_S BIT,
	USER_P_ACCESS_BY NVARCHAR(50),
	ISACTIVE_P BIT,
	DATETIMESTAMP NVARCHAR(20)
)

--DROP TABLE RemoteServerAccessInfo